name: example-serialflash-t41

on:
  push:
    paths-ignore:
    - 'docs/**'    
    - '**.md'
    - '.github/workflows/ubuntu_x64_cmake.yml'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: download toolchain
      run: |
        curl  -L "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2" --output /tmp/gcc-arm-none-eabi.tar.bz2
        mkdir -p /opt
        cd /opt
        tar xjf /tmp/gcc-arm-none-eabi.tar.bz2
        rm /tmp/gcc-arm-none-eabi.tar.bz2
        echo "/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"

    - name: build
      run: mkdir cmake-build-debug && cd cmake-build-debug && cmake .. -DCMAKE_TOOLCHAIN_FILE:FILEPATH="${{github.workspace}}/cmake/toolchains/teensy41.cmake" && make serialflash_hex

    - uses: actions/upload-artifact@v4
      with:
        name: hex file
        path: examples/SerialFlash/cmake-build-debug/serialflash.hex
